### ISSUE TITLE
Choose the port and host of each ’server’.

### ISSUE THREAD

**Issue by subarunrun0812** [yuidvg/webserv#36]
まだ満たせれていない課題要件について。
Choose the port and host of each ’server’.

同じポート番号が複数のseverコンテキストで使われてた場合、ホスト名(まだよーからん)でどのserver コンテキストの設定を使うのかを判断する必要がある。ホストとポート番号が同じやったら、始めに記述したものがdeafultになる。
これに伴い、configファイルの設計を変える選択もあるが、http のリクエストメッセージの解析中などに上記の処理をしたらいけると思う。

**Comment by yuidvg** [comment]
configファイルの設計を変えるとしたらどういう実装になる?

**Comment by subarunrun0812** [comment]
@yuidvg 

<img width="598" alt="image" src="https://github.com/yuidvg/webserv/assets/86033765/3ddd801b-3100-417e-9022-af4714cb33cd">

上記の図のように、server構造体の上位階層にport番号とhostの階層を作ったらいけると思う。
`port->host->server->location`

**Comment by yuidvg** [comment]
なるほど、これは解釈でなんとかなるとは思う。
serversの並び順は、.confファイルと同じ並び順。で合ってる？
@subarunrun0812

**Comment by subarunrun0812** [comment]
@yuidvg 
`serversの並び順は、.confファイルと同じ並び順。で合ってる？`
合ってる。
