### ISSUE TITLE
make sure  siege -b

### ISSUE THREAD

**Issue by subarunrun0812** [yuidvg/webserv#73]

**Comment by M1n01** [comment]
` siege  -c 50 -t 1M http://localhost:8080 -b `

` -c` : 同時接続ユーザーを指定でデフォルトは10

` -t` : テストの時間を指定（S = 秒、M = 分、H = 時間）

` -b` : ベンチマークモードでリクエスト間隔を置かない（デフォルトは 1 秒間のリクエスト間隔を置く）
