### ISSUE TITLE
[BUGFIX] 無限ループCGIでレスポンスが帰らない問題

### ISSUE THREAD

**Issue by M1n01** [yuidvg/webserv#77]
developを最新にし、以下のコマンドを実行した際に起きた。
`curl localhost:8080/cgi-bin/infiniteLoop.cgi`

タイムアウトつける？

**Comment by M1n01** [comment]
#67

**Comment by yuidvg** [comment]
@M1n01 つけない

**Comment by yuidvg** [comment]
あとこれはバグではない
