### ISSUE TITLE
`curl -X DELETE localhost:8080/index.html`に 400(Allowed&ファイルあるのに)

### ISSUE THREAD

**Issue by yuidvg** [yuidvg/webserv#89]

**Comment by M1n01** [comment]
@subarunrun0812 
これのupload_pathとrootの違い何ですか

### default.conf
``` 
  location /upload/ {
    allow_method GET POST DELETE;
    root www/;
    upload_path uploadPath/;
  }
```

**Comment by M1n01** [comment]
ここではrootディレクティブいらないとの結論

**Comment by M1n01** [comment]
`curl -X DELETE localhost:8080/uploadPath/hogehoge`では削除可能だった。

upload_pathディレクティブのフォルダをパスとして使わないといけないことが問題。
`curl -X DELETE localhost:8080/upload/hogehoge`で削除できるように変更したい。

**Comment by M1n01** [comment]
upload_pathディレクティブのファイルは`./<upload_path>/hogehoge`、rootの場合は`./www/hogehoge`を削除するように変更しました。
