### ISSUE TITLE
Make test cases coverage greater 

### ISSUE THREAD

**Issue by M1n01** [yuidvg/webserv#95]

**Comment by yuidvg** [comment]
- [ ] CGI 4種
- [ ] POST Upload
- [ ] DELETE
- [ ] /nosuch

**Comment by yuidvg** [comment]
これはどうなってる?

**Comment by M1n01** [comment]
@yuidvg 
telnetテストも作成したいけど、ほかはある程度は終わってるつもり。

**Comment by yuidvg** [comment]
- [ ] /nosuch: ない
- [ ] Client Redirect Response: ない
- [ ] Client Redirect Response with Document: ない
- [ ] 異なるポート: なぜ400のみ?
- [ ] UNKNOWN: ない
- [ ] Upload some file to the server and get it back.
- [ ] You have to test the CGI with the "GET" and "POST" methods
